print("^0======================================================================^7")
print("^0[^4Author^0] ^7:^0 ^0TakeFy^7")
print("^0[^3Version^0] ^7:^0 ^01.2^7")
print("^0[^2Download^0] ^7:^0 ^5https://github.com/TakeFy/tkf_autowipe/releases^7")
print("^0[^1Issues^0] ^7:^0 ^5https://github.com/TakeFy/tkf_autowipe/issues^7")
print("^0======================================================================^7")
